### ISSUE TITLE
Mount of fluent-bit config should include all files

### ISSUE THREAD

**Issue by hyffrank** [h3poteto/fluentd-sidecar-injector#143]
Volume mount of fluent-bit config is now only including fluent-bit.conf, which doesn't work if input/output/parser configuration files are defined seperately with @INCLUDE or Parsers_File declaration, especially for parser files since Fluent-bit even doesn't support defining parsers inside the main config file directly which means we cannot work around the "parsers".

**Comment by hyffrank** [comment]
Close due to duplication. Issue has been addressed with PR [https://github.com/h3poteto/fluentd-sidecar-injector/pull/138](url)

**Comment by h3poteto** [comment]
Thank you
